---

#args:
#  type: #db - Backup a database
#  type: #dir - Backup a directory
#  type: #sub - backup each sub directories into separate files

#  dst_file: #No extension
#  exc: _*/\* wp-content/\*
#  zip_args: #-FS, -s 50m
#- debug: msg="{{args}}"

- name: BAK_DIR {{args.bak_args.name}} #bak_dev01_nspwww
  when: args.bak_args.type=="dir"
  vars:
    my_args:
      zip_args: "{{args.zip_args}}"
      src_dir: "{{args.src_root}}/{{args.bak_args.path}}"   #src_dir now include item path
      #src_item: "{{args.bak_args.path or '.'}}"
      src_item: "." #'.' is to ackup all files
      dst_file: "{{args.dst_root}}/{{args.bak_args.name}}"
      #Manipulate then concat (adding " " at the end.
      exc: "{%for item in args.bak_args.exc%} -x'!{{item}}'{%endfor%} "
    cmd: >
      cd {{my_args.src_dir}} ;
      7z a {{my_args.dst_file}}.zip {{my_args.src_item}} {{my_args.exc}}
  #debug: {msg: "{{my_args.exc}} *** {{cmd}}"}
  shell: "{{cmd}}"
