---

- name: Clear DB
  block:
  - name: Drop foreign keys constrains
    community.mysql.mysql_query:
        query: SELECT TABLE_NAME,CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE='FOREIGN KEY'
        login_db: "{{clear_db_opts.db_name}}"
        login_user:         "{{clear_db_opts.login_user           | default(omit) }}"
        login_unix_socket:  "{{clear_db_opts.login_unix_socket    | default(omit) }}"
        login_password:     "{{clear_db_opts.login_password       | default(omit) }}"
    register: output
  - debug: var=output
  - meta: end_play

  - name: List tables
    community.mysql.mysql_query:
      login_db: "{{clear_db_opts.db_name}}"
      query: "SELECT table_name FROM information_schema.tables WHERE table_schema = '{{clear_db_opts.db_name}}'"
    register: output
  - debug: var=output
  - meta: end_play
  
  - name: Drop all tables in DB:{{clear_db_opts.db_name}}
    vars:
      #qry: "[].table_name.join('' ,['DROP TABLE `',@,'`;'])"
      #sql: "START TRANSACTION; {{ output.query_result[0]|to_json|from_json|json_query( qry ) | join(' ') }}; COMMIT;"
      qry_drop: "[].table_name.join('' ,['`',@,'`'])"
      sql_drop: "DROP TABLE {{ output.query_result[0]|to_json|from_json|json_query( qry_drop ) | join(', ') }};"
      qry_fk0: >
        [].table_name.join('',['
        SET @table_name = \'',@,'\';
        SET @sql="SELECT IF(
        (SELECT true FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE()
        AND TABLE_NAME=@table_name AND CONSTRAINT_NAME=\'fk_name\' AND CONSTRAINT_TYPE=\'FOREIGN KEY\') = true
        ,\'ALTER TABLE @table_name drop foreign key fk_name\'
        ,\'SELECT 1\'
        )";
        PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;'])
      qry_fk: >
        [].table_name.join('',['
        SET @table_name = \'',@,'\';
        SET @sql="SELECT IF(
        (SELECT true FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE()
        AND TABLE_NAME=@table_name AND CONSTRAINT_NAME=\'fk_name\' AND CONSTRAINT_TYPE=\'FOREIGN KEY\') = true
        ,\'ALTER TABLE @table_name drop foreign key fk_name\'
        ,\'SELECT 1\'
        )";
        PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;'])
      sql_fk0: "{{ output.query_result[0]|to_json|from_json|json_query( qry_fk ) | join(' ') }}"
      sql_fk1: "{{ (sql_fk0+sql_drop)|regex_replace(';$','') }}"
      sql_fk: "{{ sql_fk1.split(';') }}"
      #sql_truncate: "TRUNCATE TABLE {{ output.query_result[0]|to_json|from_json|json_query( qry ) | join(', ') }};"
    block:
    - debug: var=qry_fk
    - debug: var=sql_fk
    - community.mysql.mysql_query:
        query: "{{sql_fk}}"
        login_db: "{{clear_db_opts.db_name}}"
        login_user:         "{{clear_db_opts.login_user           | default(omit) }}"
        login_unix_socket:  "{{clear_db_opts.login_unix_socket    | default(omit) }}"
        login_password:     "{{clear_db_opts.login_password       | default(omit) }}"
      register: output
    - debug: var=output
