---

- name: Clear DB
  block:
  - name: Get foreign keys constrain list
    community.mysql.mysql_query:
        #query: SELECT TABLE_NAME,CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE='FOREIGN KEY'
        query: >
          SELECT TABLE_NAME,CONSTRAINT_NAME FROM information_schema.TABLE_CONSTRAINTS
          WHERE TABLE_SCHEMA='{{clear_db_opts.db_name}}' AND CONSTRAINT_TYPE='FOREIGN KEY'
        login_db: "{{clear_db_opts.db_name}}"
        login_user:         "{{clear_db_opts.login_user           | default(omit) }}"
        login_unix_socket:  "{{clear_db_opts.login_unix_socket    | default(omit) }}"
        login_password:     "{{clear_db_opts.login_password       | default(omit) }}"
    register: out_drop_fk
  - debug: var=out_drop_fk

  - name: Get table list
    community.mysql.mysql_query:
      login_db: "{{clear_db_opts.db_name}}"
      query: "SELECT table_name FROM information_schema.tables WHERE table_schema = '{{clear_db_opts.db_name}}'"
    register: out_table_list

  - name: Gen sql_drop_table DB={{clear_db_opts.db_name}}
    vars:
      qry_drop_fk: "[].join('' ,['ALTER TABLE `',@.TABLE_NAME,'` DROP FOREIGN KEY `',@.CONSTRAINT_NAME,'`'])"
      sql_drop_fk: "{{ out_drop_fk.query_result[0]|to_json|from_json|json_query( qry_drop_fk ) | join('; ') }};"
      qry_drop_table: "[].table_name.join('' ,['`',@,'`'])"
      sql_drop_table: "DROP TABLE {{ out_table_list.query_result[0]|to_json|from_json|json_query( qry_drop_table ) | join(', ') }};"
    community.mysql.mysql_query:
      query:    "{{ ( (sql_drop_fk + sql_drop_table)|regex_replace(';$','') ).split(';') }}"
      login_db: "{{clear_db_opts.db_name}}"
      login_user:         "{{clear_db_opts.login_user           | default(omit) }}"
      login_unix_socket:  "{{clear_db_opts.login_unix_socket    | default(omit) }}"
      login_password:     "{{clear_db_opts.login_password       | default(omit) }}"
    #debug: var=query
    register: output
  - debug: var=output
